const DAO_TOKENS_ADDRESS = ""
const DAO_VOTING_ADDRESS = ""
const DAO_TIME_LOCK_ADDRESS = ""
const FLAG_ADDRESS = ""

export default {
	DAO_TOKENS_ADDRESS,
	DAO_VOTING_ADDRESS,
	FLAG_ADDRESS,
	DAO_TIME_LOCK_ADDRESS
}
